### ISSUE TITLE
Python version limitation isn't respected

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#114]
When updating packages (e.g. in #111, #112) I run into issues with building aplpy for python3.6. However adding the ``python: '<3.6'`` limitations in ``reqiorements.yml`` doesn't seem to have any effect, it still tries to build the packages for 3.6: https://travis-ci.org/astropy/conda-channel-astropy/jobs/187418163#L1093

**Comment by bsipocz** [comment]
It's rather weird that locally this works perfectly and the same test branch that fails on travis gives this result for e.g. aplpy
```
Resolved dependencies, will be built in the following order: 
	aplpy-1.1.1-py27_0 (will be built: False)
	aplpy-1.1.1-py34_0 (will be built: False)
	aplpy-1.1.1-py35_0 (will be built: False)
```

versus:

```	
        aplpy-1.1.1-py27_0 (will be built: False)
	aplpy-1.1.1-py35_0 (will be built: False)
	aplpy-1.1.1-py36_0 (will be built: True)
```

**Comment by mwcraig** [comment]
I think the issue is (or was) here: https://github.com/astropy/conda-channel-astropy/blob/master/.travis.yml#L21

In the travis build you linked, `PYTHON_BUILD_RESTRICTIONS` was still `2.7*|>=3.4`, and for some reason that wins over the python version restriction in requirements.yml.

**Comment by bsipocz** [comment]
@mwcraig - I kept that variable with the same value locally, and it worked. Will try to test it on a linux box later.

**Comment by bsipocz** [comment]
@mwcraig - It looks like that conda.resolve doesn't like the ``'<3.6'`` limitation, but works as expected with ``'<3.6*'``. I'm gradually limiting packages that for some reason fail to build in #120, while keeping track of things in #119.

**Comment by mwcraig** [comment]
@bsipocz -- I think that is because it does not see `3.6.0` as the same as `3.6`, but `3.6*` matches `3.6.0`.

**Comment by bsipocz** [comment]
Fair enough, though it still seems to be a bug to me. Probably we should report it to conda?

**Comment by mwcraig** [comment]
Yeah, I suppose you are right. It makes sense the `3.6 != 3.6.0` but certainly it ought to be the case that `3.5.2<3.6`
