### ISSUE TITLE
Build packages for python3.6

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#119]
I foresee that this issue will be solved gradually with multiple PRs, so it may be helpful to have one central place to track the progress. Some package releases may genuinely be incompatible with python3.6, if we know such cases a link to the relevant issues could be referenced here, too.

The following table can be used to track which packages are compatible as can be build successfully:

* [x] APLpy
* [x] asdf
* [x] astro-gala
* [x] astroML
* [x] astroplan
* [x] astropy-helpers
* [x] astroquery
* [x] astroscrappy
* [x] ccdproc
* [x] cluster-lensing
* [x] corner
* [x] emcee
* [x] extinction
* [x] gammapy
* [x] ginga
* [x] glueviz
* [x] gwcs
* [x] halotools
* [x] hgtools
* [x] imexam
* [x] iminuit
* [x] lmfit
* [ ] maltpynt
* [ ] montage-wrapper
* [x] naima
* [ ] omnifit
* [x] photutils
* [x] pydl
* [ ] pyephem
* [x] pyregion
* [x] pytest-arraydiff
* [x] pytest-mpl
* [x] python-cpl
* [x] regions
* [x] reproject
* [x] sncosmo
* [x] spectral-cube
* [x] specutils
* [ ] spherical-geometry
* [x] wcsaxes

The remaining packages have the following issues with them:

* latest release incompatibility with Configparser: ``montage-wrapper``, ``omnifit``, ``maltpynt``, ``gammapy`` (a newer version is available in #99)

* other reason: ``pyephem``

There are other packages that conda.resolve deems unbuildable probably due to missing dependencies:  ``spherical-geometry``, ``ccdproc``

**Comment by bsipocz** [comment]
Weird, sncosmo built successfully on my fork here: https://travis-ci.org/bsipocz/conda-channel-astropy/builds/190302604, but it failed in master due to the missing numpy issue.

**Comment by mwcraig** [comment]
@bsipocz thanks × 10^{6}!

**Comment by mwcraig** [comment]
I assume the numpy issue is that it is not available for old numpy/python 3.6? That is the one downside of conda (and conda-forge) -- they will not build binaries of older numpy + new python.

**Comment by bsipocz** [comment]
Yes, exactly. We used to build the old versions and hosted in ``astropy-ci-extras``, but that was before these repos brake into two and thus I couldn't find the scripts. Maybe they were built manually?

**Comment by mwcraig** [comment]
One of the ccdproc blockers is scikit-image, which does not exist on defaults for python 3.6 yet.

**Comment by bsipocz** [comment]
it is available on conda-forge (maybe it's super recent?) I'll try and restart the latest build, that should pick it up in that case.

**Comment by astrofrog** [comment]
Yes, I did the PR to add it on conda-forge a couple of days ago

**Comment by leblancfg** [comment]
Hi all,

Wanted to see if it's be possible to get more details regarding PyEphem -- does anyone remember the 'other reason'? Anything related to https://github.com/brandon-rhodes/pyephem/issues/118?

Can't compile C++ locally here on Windows because of restrictions, so your conda channel is a real godsend. But I probably wouldn't be able to submit a PR, sorry.

**Comment by bsipocz** [comment]
@leblancfg - pyephem is not an affiliated package, and we only built it here in this channel as it's a dependency of one of our affiliates. I'll have another look at the problem, but won't have time to spend much time on it unless it's something trivial.

**Comment by bsipocz** [comment]
@leblancfg - I don't see trivially what goes wrong, here is the full build log: https://travis-ci.org/bsipocz/conda-channel-astropy/builds/228929922#L1153

**Comment by brandon-rhodes** [comment]
From the error output, my guess is that you are using options to `install` that only exist when the 3rd party `setuptools` package is used by a project's `setup.py`, whereas PyEphem has always used a plain:
```
from distutils.core import setup, Extension
```
— import at the top of its `setup.py` in case folks don't have access to `setuptools`. Maybe if I ever release a newer version (which is a huge weekend-long ordeal at this point, given that both Mac and Windows versions have to be build, and I'm not sure when I'll next try to attempt it) I will add a conditional import that tries to `import setuptools` if it's possible but fails silently if it's not?

I am steering most users towards Skyfield, my next-generation replacement for PyEphem that is pure Python, doesn't need to compile, and has `numpy` as its only binary dependency.

**Comment by mwcraig** [comment]
Can we close this now, @bsipocz ?

**Comment by bsipocz** [comment]
Oh, sure, we did everything we could for this one I think.
