### ISSUE TITLE
spherical-geometry causes Python 3.5 downgrade

### ISSUE THREAD

**Issue by pllim** [astropy/conda-channel-astropy#155]
1. I did not expect to see `spherical-geometry` coming from `astropy` channel (didn't see an entry for it in the recipes folder).
2. Then, I am further confused by the required downgrade from 3.5.3 to 3.5.1. 
3. To top it off, the version (1.0.6) is not the latest release (1.0.10). See https://github.com/spacetelescope/sphere

```
$ conda install spherical-geometry
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment .../anaconda/envs/dadf:

The following NEW packages will be INSTALLED:

    spherical-geometry: 1.0.6-py35_0 astropy

The following packages will be DOWNGRADED due to dependency conflicts:

    python:             3.5.3-1              --> 3.5.1-5
```

**Comment by bsipocz** [comment]
@pllim - I'm not yet sure about the python version, but can confirm that 1.0.6 is indeed the latest official version, we cannot do anything with releases that are not uploaded to pypi and thus not pip installable:

https://pypi.python.org/pypi/spherical-geometry

**Comment by bsipocz** [comment]
They python version issue: we had to limit the version for ``  python: '<3.5.2'`` for 1.0.6, due to the ConfigParser issue that wasn't yet fix in that release. So if you upload 1.0.10 to pypi, both issues can be solved fairly quickly.

**Comment by pllim** [comment]
Is there no way to grab it from GitHub release? I don't have access to its PyPi account and no sure who does.

**Comment by bsipocz** [comment]
@pllim - That would be an ugly hack, and quite non-standard. I think @bernie-simon must have access, he's listed there as owner and did latest upload.

**Comment by pllim** [comment]
Ah, okay. I was confused by @mdboom listed as "author". I have opened spacetelescope/sphere#102 for the outdated PyPi problem.

On our side though, in order to support AstroConda, we give more priority to GitHub releases rather than PyPi. FYI.

**Comment by bsipocz** [comment]
Ah, ok. Though those are not really releases but just git tags, don't they?

**Comment by pllim** [comment]
Probably but they are listed as "releases" by GitHub -- https://github.com/spacetelescope/sphere/releases

**Comment by bsipocz** [comment]
oh, yes. They do some packaging, but then basically all your Manifest, etc is ignored and everything is just simply gets zipped up.

**Comment by mwcraig** [comment]
I'm pretty sure this fixed (or at least no longer relevant), so I'm closing. Feel free to re-open it if needed, though.
