### ISSUE TITLE
photutils 0.4.1 builds not mirrored from conda-forge

### ISSUE THREAD

**Issue by larrybradley** [astropy/conda-channel-astropy#171]
The 0.5 builds were mirrored from `conda-forge`, but not the 0.4.1 builds.

CC: @mwcraig

**Comment by mwcraig** [comment]
I think by default it only copies the most recent version....will try to fix later tonight (or at least manually copy)

**Comment by larrybradley** [comment]
Thanks, @mwcraig!

**Comment by mwcraig** [comment]
I just did a manual copy, will work on the copy script over the weekend. Turns out some minor things have change in conda since the last time the copying code was modified a year ago!

**Comment by mwcraig** [comment]
Closing, since copying all versions is now always done.
