### ISSUE TITLE
Astropy LTS releases missing for Python 2.7

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-channel-astropy#174]
It looks like we aren't copying over the Python 2.7 builds for Astropy LTS: https://anaconda.org/astropy/astropy/files?version=2.0.10

@mwcraig - any idea what could be causing this?

We're also missing MacOS X and Windows but that's an issue on the conda-forge side (https://github.com/conda-forge/astropy-feedstock/issues/50)

**Comment by mwcraig** [comment]
Will troubleshoot later tonight. Looks like it hits a duplicate package when copying astropy and then stops....not sure why.

**Comment by mwcraig** [comment]
Copied semi-manually and opened a PR to conda-sync to fix here too.
