### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-channel-astropy#175]
It looks like the following affiliated packages are missing from the astropy channel (based on  http://www.astropy.org/astropy-dashboard/status.html):

- [x] baseband
- [x] corral
- [x] dust_extinction ([on conda-forge](https://github.com/conda-forge/dust_extinction-feedstock))
- [x] hendrics ([on conda-forge](https://github.com/conda-forge/hendrics-feedstock))
- [x] linetools
- [x] marxs (pull request opened at https://github.com/conda-forge/staged-recipes/pull/8806)
- [x] pyspeckit
- [ ] Saba (not attempting until there is a new release)
- [x] stingray ([on conda-forge](https://github.com/conda-forge/stingray-feedstock))
- [x] synphot
- [x] feets (open PR: https://github.com/conda-forge/staged-recipes/pull/8803)

**Comment by mwcraig** [comment]
On my agenda for today...

**Comment by mwcraig** [comment]
Closing; saba hasn't been packaged, but the last release is over 3 years old and sherpa has evolved some since then.

**Comment by bsipocz** [comment]
Maybe we can ping @hamogu to cut a release? There has been quite a lot of change in master since the last release.

**Comment by hamogu** [comment]
I was planning a release of Saba for December, when I expect the first py 3 only Sherpa. That way I save myself the worry about checking py2 backwards compatibility and a few more weeks won't hurt saba at this point.
