### ISSUE TITLE
pytest-astropy not up to date in astropy channel

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-channel-astropy#180]
It looks like pytest-astropy 0.8 is missing from conda-forge and the astropy channel - I think because we first need to create a recipe for pytest-subpackage-filter (added as a dependency in pytest-astropy 0.8). Anyone able to set up the recipe for pytest-subpackage-filter?

**Comment by mwcraig** [comment]
I can do that this afternoon.

**Comment by mwcraig** [comment]
See https://github.com/conda-forge/staged-recipes/pull/11820

**Comment by bsipocz** [comment]
I'm more and more on the side that we shouldn't conda package the infrastructure packages, but suggest and only support pip install for them. That would resolve the issues people running into with outdated (but conda up-to-date) plugins, etc.

**Comment by mwcraig** [comment]
I'm curious to see if adding automerge to  feedstocks will help (though in this case it wouldn't have).T auto-tick-bot + automerge should make keeping this up to date painless. 

I do wonder whether we still need our own channel.

**Comment by bsipocz** [comment]
automerge is great, but it wouldn't have helperd here. 

I'm +1 to keep the own channel. It helps to ensure default is used along with the astro packages rather than the conda forged builds.
