### ISSUE TITLE
ROADMAP: Retiring astropy conda channel

### ISSUE THREAD

**Issue by pllim** [astropy/conda-channel-astropy#187]
As discussed offline, here is the proposed retirement roadmap for `astropy` conda channel.

p.s. Feel free to correct me if I misunderstood.

### Motivation

The `astropy` conda channel is just a copy of the project's packages in `conda-forge`.  While there is little cost to keeping this channel, there is also little reason to. Futhermore, the command of `conda install astropy -c astropy` confused some users who were not familiar with `conda`, as one needs to type in `astropy` twice.

#### Immediately

Replace all mention of `-c astropy` with `-c conda-forge`. I replaced what I could find in the `astropy` organization below, but I could have missed some.

  * astropy/astropy#11111
  * astropy/astropy-tutorials#471
  * astropy/astropy.github.com#415
  * astropy/astroplan#491
  * astropy/astroquery#1908
  * astropy/ccdproc#749
  * astropy/halotools#1002
  * astropy/regions#329
  * astropy/reproject#244
  * astropy/sphinx-automodapi#120
  * Non-org bonus: spacetelescope/notebooks#153

#### Near future

Send out a notice out to the usual Astropy communication channels (astropy? astropy-dev? astropy-core-maintainers?) to encourage people to use `conda-forge` instead of `astropy` conda channel.

#### At the next LTS release (`astropy` 5.0)

Retire `astropy` conda channel; either:

  * Simply stop updating it (and archive?); **OR**
  * Nuke all the packages off it but keep the name.

(Either way, we cannot let go of the name lest malicious actor claims it.)

Someone also mentioned "relabel them to get around breaking old installs."

**Comment by astrofrog** [comment]
Just for the record, the reason we had the separate channel was to avoid having users have to opt in to the whole conda-forge ecosystem. However, maintaining this channel is a maintenance burden and I'm happy to just direct users to conda-forge or defaults.

**Comment by pllim** [comment]
Not sure what you mean by the "whole conda-forge ecosystem." As a `conda` user myself using Miniconda, I pick and choose what I install from `conda-forge`. I set `conda-forge` as a secondary channel after `defaults`. It is not like the Anaconda version where you get a bunch of stuff you didn't ask for. Can you please clarify?

**Comment by astrofrog** [comment]
Yes - for example if you `conda install -c astropy astropy` it will just use astropy from conda-forge but e.g. numpy from defaults. If you `conda install -c conda-forge astropy` you might also pull in e.g. numpy from conda-forge. Don't think this is really a problem but for packages like astropy which have few dependenices but in some cases some conda-forge packages don't play well with defaults (e.g for PyQt there have sometimes even been segfaults due to the mixing of conda-forge and defaults). Anyway I think realistically things will work fine here so 👍 on the roadmap.

**Comment by pllim** [comment]
Re: https://github.com/astropy/conda-channel-astropy/issues/187#issuecomment-736062544 -- Ah, good point. As far as `numpy` is concerned, I have installed it from `defaults`, `conda-forge`, and `pip` at some point. `conda` complains about "your env might be messed up" (paraphrased) but things still work. If we really recommend `numpy` from, say, `defaults`, perhaps it is clearer to put that in the install doc rather than to maintain a whole separate channel.

**Comment by taldcroft** [comment]
I'm also a little concerned about this and I have seen conda pulling in not only numpy but even Python and many other packages from conda-forge if conda-forge is in the channel list. I'm careful about channels and checking things, but my worry is that users will accidentally muck up their environment without realizing.

**Comment by mwcraig** [comment]
To clarify a little bit, the astropy conda channel wouldn't stop being updated any time soon.Right now the conda ecosystem seems somewhat unsettled to me. The default channel does not seem to be upgrading packages as regularly as it used to, the solver often gives surprising results that are nearly impossible to interpret, and conda-forge sometimes has broken packages. 

The thought was to try changing the instructions and see what happens. If we hear a bunch of issues/complaints then we for sure need to keep the astropy channel around. If we don't, then we can consider not updating it anymore.

At the moment I'm pretty reluctant to delete packages from the channel, ever, so that folks can always reproduce past environments.

**Comment by pllim** [comment]
It has been 4 years. Is it time to kill the channel and archive this repo?

**Comment by mwcraig** [comment]
I think so, yes

**Comment by pllim** [comment]
@mwcraig , what are the remaining action items besides archiving this repository? Do we need to contact Anaconda somehow? Send out memo?

**Comment by mwcraig** [comment]
I don't think we need to do anything but I'm a little confused by one thing: apparently dev builds are still getting uploaded to the astropy conda channel -- https://anaconda.org/astropy/astropy/files

Looks photutils is also uploading packages there: https://anaconda.org/astropy/photutils/files

I don't think that affects whether we archive this repo -- it is not the place that is generating those packages.

**Comment by astrofrog** [comment]
I'd be fine with dropping the astropy channel (I did the same with the glueviz channel)

**Comment by astrofrog** [comment]
> dev builds are still getting uploaded to the astropy conda channel 

Ah yes we use it for all the nightly wheels!

**Comment by pllim** [comment]
I thought for nightly wheel, we use PyPI index. How is that related to astropy conda channel? AFAIK we never ask people to `conda install astropy -c astropy` for dev wheels.

**Comment by pllim** [comment]
> Ah yes we use it for all the nightly wheels!

@astrofrog , so what does this mean? We still need this repo?

**Comment by astrofrog** [comment]
No we don't need this repo. We upload the wheels directly from GitHub actions.

We should probably also remove all the conda packages from the astropy channel?

**Comment by pllim** [comment]
> We should probably also remove all the conda packages from the astropy channel?

@mwcraig , do we have to do this? Thought you said astropy channel is just a mirror of conda-forge or something?

Anyways, can we archive this repo now?

**Comment by mwcraig** [comment]
I'd mildly lean against deleting the packages in case anyone out there wants to reproduce some old installation or something, but the repo can be archived for sure

**Comment by pllim** [comment]
Archiving then. Thanks, all!
