### ISSUE TITLE
Syncing of versions stopped

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#190]
New releases haven't been synced to the channel since March as the GHA is not triggered currently from cron.

**Comment by mwcraig** [comment]
Thanks, will fix this afternoon (or at least try to fix)...

**Comment by mwcraig** [comment]
A push-triggered copy [just succeeded](https://github.com/astropy/conda-channel-astropy/runs/3415905455?check_suite_focus=true), will see about the cron job in ~1 hour.

**Comment by mwcraig** [comment]
cron job is [running now](https://github.com/astropy/conda-channel-astropy/runs/3416145227?check_suite_focus=true) too so https://github.com/astropy/conda-channel-astropy/runs/3416145227?check_suite_focus=true closing this. Thanks for reporting it!
