### ISSUE TITLE
Fix miniconda version on appveyor

### ISSUE THREAD

**Issue by mwcraig** [astropy/conda-channel-astropy#21]
Right now it is pegged at 2.7, essentially. Oddly, the python 3.x packages seem to be building just fine.

**Comment by bsipocz** [comment]
My understanding is that the miniconda version doesn't matter as if one requires a different python version in an environment it installs it, rather than use shipped version.

**Comment by mwcraig** [comment]
In principle that is the case, but in practice (at least in the past), the compiler environment set up in `%CMD_IN_EVN%` was determined by the installed python rather than `CONDA_PY`.

**Comment by mwcraig** [comment]
I think you were right about this, @bsipocz, so I'm closing it...
