### ISSUE TITLE
Switch from obvious-ci to conda-build-all

### ISSUE THREAD

**Issue by mwcraig** [astropy/conda-channel-astropy#39]
I've done this on astropy/conda-channel-ci-extras but not here....however, it would be very useful.

**Comment by bsipocz** [comment]
@mwcraig - Any chance to do this while you're still conda sprinting at scipy?  Looks like you've already started it in #12 :)

**Comment by mwcraig** [comment]
Yep, sprints start tomorrow!

Thanks,
Matt Craig

**Comment by mwcraig** [comment]
This has been merged, so I'm closing, but it turns out the main advantage I thought it would have (cross-channel copying from conda-forge to astropy) is broken. That issue belongs in conda-build-all, though.
