### ISSUE TITLE
Make it configurable which package can use conda-forge

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#56]
I would be brilliant to be able to set for each package whether we want to use conda-forge for it or not. E.g. when updating one package, we can't limit another one's version in case there is a newer conda-forge recipe for it.

I run into this [error](https://travis-ci.org/astropy/conda-channel-astropy/jobs/147033797#L409) with lmfit when tried to make #51 work. In this case this will be fine, but we could potentially run into problems with other packages.

**Comment by mwcraig** [comment]
So the idea would be to allow the version to be updated from the conda-forge version? Or that we'd have a flag that would allow the overriding? 

One option is just to omit the package version...

**Comment by bsipocz** [comment]
I though about a third option, not to look at conda-forge at all. This can be then either True or False by default.

**Comment by bsipocz** [comment]
btw now that the conda-forge copies are working, do we want to copy glue over here to the `astropy` channel?

**Comment by bsipocz** [comment]
> One option is just to omit the package version...

Can we do this already? E.g. for keyring, lmfit, etc if we omit the version would it pick up the latest from conda-forge, and updates it automatically when there is a new one over there?

**Comment by mwcraig** [comment]
Closing since now everything uses conda-forge 😃😬
