### ISSUE TITLE
Figure out fail when copying package 

### ISSUE THREAD

**Issue by mwcraig** [astropy/conda-channel-astropy#73]
See, e.g. https://travis-ci.org/astropy/conda-channel-astropy/jobs/153149017#L2672

@bsipocz -- we should hold off on merging PRs until this is figured out...

**Comment by bsipocz** [comment]
@mwcraig - I've pushed a commit directly to master to test whether the copying of lmfit is indeed the problematic point. It seems that we get a 409 error that would usually mean that lmfit in astropy is newer that in conda-forge. However looking at them they look exactly the same. 

It's strange though that in the last working build there was no attempt to copy lmfit.

**Comment by bsipocz** [comment]
Indeed lmfit is the problematic point, so I would keep it commented out from `requirements.yml` as the workaround until there is a new release of it, or until this issue is understood.

**Comment by mwcraig** [comment]
Closing, since copying now works...
