### ISSUE TITLE
Can't find astroml-0.3 package

### ISSUE THREAD

**Issue by JuanCab** [astropy/conda-channel-astropy#76]
Running 'conda install astroml' under a python 2.7 installation of Anaconda 3.0 currently results in:

```
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/osx-64/astroml-0.3-py27_0.tar.bz2: https://conda.anaconda.org/astropy/osx-64/astroml-0.3-py27_0.tar.bz2
```

I can workaround this using:

conda install -c astropy astroml=0.3

which succeeds in installing astroml-0.3-0.3-np19py27_0 (and not astroml-0.3-py27_0).

**Comment by mwcraig** [comment]
Thanks, I'll to get it fixed this weekend. In the meantime you should be able to pip install astroml to avoid the numpy version conflict.

**Comment by mwcraig** [comment]
This should be fixed in a few minutes...
