### ISSUE TITLE
Adding gala conda build

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#84]
As it's an affiliated package it would make sense for the sake of completeness to add a conda build here, too. What do you think @adrn?

**Comment by adrn** [comment]
Yea, sounds like a good idea! I've never done this but will take a look at examples from other packages.

**Comment by bsipocz** [comment]
Based on your travis file it should be quite standard, so probably there won't be any major problems. Do you want me to do it?

**Comment by adrn** [comment]
Sure, but ping me in the PR! Thanks
